/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExerciseLayout: typeof import('./components/ExerciseLayout.vue')['default']
    KeyHint: typeof import('./components/KeyHint.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningTimer: typeof import('./components/RunningTimer.vue')['default']
    TemplateFooter: typeof import('./components/TemplateFooter.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
